// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiA0riIsuSAAXieSVQ4akRqAIY4JmEEDE',
    appId: '1:695449776464:web:8c775ae7de21c5c64d7c55',
    messagingSenderId: '695449776464',
    projectId: 'sceneit-39c58',
    authDomain: 'sceneit-39c58.firebaseapp.com',
    storageBucket: 'sceneit-39c58.firebasestorage.app',
    measurementId: 'G-HYRRFF5G1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8TerhvXKb6laS-HxYfg3w9hQN6DLmLck',
    appId: '1:695449776464:android:90fa5aba6f30088d4d7c55',
    messagingSenderId: '695449776464',
    projectId: 'sceneit-39c58',
    storageBucket: 'sceneit-39c58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHn2TFo4-QMkEt3adkrM34Tk7wsVC0PTw',
    appId: '1:695449776464:ios:19f72966403ccb124d7c55',
    messagingSenderId: '695449776464',
    projectId: 'sceneit-39c58',
    storageBucket: 'sceneit-39c58.firebasestorage.app',
    iosBundleId: 'com.example.sceneit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHn2TFo4-QMkEt3adkrM34Tk7wsVC0PTw',
    appId: '1:695449776464:ios:19f72966403ccb124d7c55',
    messagingSenderId: '695449776464',
    projectId: 'sceneit-39c58',
    storageBucket: 'sceneit-39c58.firebasestorage.app',
    iosBundleId: 'com.example.sceneit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiA0riIsuSAAXieSVQ4akRqAIY4JmEEDE',
    appId: '1:695449776464:web:364fa11796af1ca64d7c55',
    messagingSenderId: '695449776464',
    projectId: 'sceneit-39c58',
    authDomain: 'sceneit-39c58.firebaseapp.com',
    storageBucket: 'sceneit-39c58.firebasestorage.app',
    measurementId: 'G-TKBS0K99XE',
  );
}
